### ISSUE TITLE
How to make downshift just behave like text box if user does not want to select from selection

### ISSUE THREAD

**Issue by kavink** [paypal/downshift#333] opened 2018-02-16 17:14 UTC
I am trying to figure how do I make Downshift Input just behave like a text box if there are no suggestions or user wants to enter something free text and ignore suggestion . 

Any thoughts ?

**Comment by newyork-anthonyng** [comment] 2018-02-16 17:49
What's awesome about `downshift` is that it gives you the power to render what you want.

Take a look at this [CodeSandbox demo](https://codesandbox.io/s/oo88mkoq56) that I forked from the `simple downshift` example.

Inside of the `render` method, I added an `if` statement to check if there are suggestions:
```jsx
<Downshift
  render={({ getInputProps }) => {
    if (items.length === 0) return <input type="text" placeholder="Plain ol' textbox" />

    return <input {...getInputProps()} />
  }}
/>
```

**Comment by kentcdodds** [comment] 2018-02-16 19:01
Thanks @newyork-anthonyng!

Also @kavink, there are several examples on the README and I'm pretty sure one or two of them are what you're looking for. I think it's the type ahead one.

**Comment by kentcdodds** [comment] 2018-02-16 19:01
I'm going to go ahead and close this as it's not actionable, but feel free to continue asking questions and hopefully someone watching the repo can help answer.

**Closed by kentcdodds** 2018-02-16 19:01 UTC

**Comment by kavink** [comment] 2018-02-16 19:34
@kentcdodds  Thanks for comments, I did look at type ahead one, But ```onStateChange``` user typing and selecting does not actually reflect in submitted form. Any thoughts how I can workaround it because as soon I leave the text box, it resets the field in fold and does not persist user option.

@newyork-anthonyng Thanks, that solves issue when there are no suggestions. Im still trying to nail down when there are suggestions but user wants to submit something else. Following Type ahead example, I have ```onStateChange``` function which does exactly as ```onChange```. But then when I leave the box, the form value resets.

**Comment by newyork-anthonyng** [comment] 2018-02-16 22:26
@kavink Could you provide an example of this in CodeSandbox?

When I look at the [TypeAhead example on CodeSandbox](https://codesandbox.io/s/82m2px40q9), the behavior isn't what you describe.
For example:
* I type `ap` into the input field
* I press `tab` to leave the input field
* The `selected fruit` text reads `ap`. The input field did not reset.

**Comment by kavink** [comment] 2018-02-16 23:57
@newyork-anthonyng  here is an example: https://codesandbox.io/s/zlv7kmmyp

**Comment by kavink** [comment] 2018-02-17 00:09
@newyork-anthonyng @kentcdodds You can try entering ```sssss``` into the ```fruit``` field , and leave click elsewhere in screen you will see the data is removed/reset from Form. (form data is in the bottom)

**Comment by kentcdodds** [comment] 2018-02-17 00:17
I gave it a quick look and I can tell you there are definitely a few ways to accomplish what you want to. But I'm afraid I don't have time at the moment to show you any of them. Just posting this to say don't lose hope! This is definitely possible (without any weird hacks).

**Comment by kavink** [comment] 2018-02-17 00:34
@kentcdodds No worries, Even a pointer is enough on why would it reset field on leaving if nothing is selected. Or if you can point me in right direction.

**Comment by kentcdodds** [comment] 2018-02-17 00:39
Downshift has to make decisions and have some opinions on the user experience. One decision that it has made is to [call `reset`  when the user blurs the input](https://github.com/paypal/downshift/blob/83cb60beae498f48c454f9407e7a6bcf256879cb/src/downshift.js#L686-L690). The reset function will reset the input's value to the `itemToString` value of the `selectedItem`.

Downshift exposes a few methods to override these decisions. You can add your own event handler and call `event.preventDefault()` which will prevent downshift's event handlers from running. You can override the prop entirely with: `<input {...getInputProps({})} onBlur={() => {/* overridden */}} />`. Or you can use a `stateReducer` or control props (check the docs).

There are several options here. The integration with final form may make things slightly challenging. Once you figure out something good, a simple example we could add to the README would be appreciated!

I hope that helps.

**Comment by kavink** [comment] 2018-02-17 01:02
In the example I posted, thats what I had done. Tried to override onBlur. which seems to work in this example: https://codesandbox.io/s/k594964z13 but not in mine. Same piece of code.  Anyways will keep digging through, now I know some background why its happening .
```
     {...getInputProps({
                name: input.name,
                onBlur: input.blur
              })}
```

**Comment by newyork-anthonyng** [comment] 2018-02-17 02:40
@kavink I took a look at your example.

Making the change below seems to make the `onBlur` work as you wanted it to.
```diff
<input
    {...getInputProps({
        name: input.name,
-      onBlur: input.onBlur
+      onBlur: (e) => {
+          e.preventDefault();
+          input.onBlur(e);
+      }
    })}
/>
```

I think the difference between your example using `react-final-form` and `redux-form` is how they handle `onBlur` events.

In `react-final-form`, it looks like `e.preventDefault` is not called ([see relevant lines here](https://github.com/final-form/react-final-form/blob/5dd92af29db37803516099924e0618973ad4e73a/src/Field.js#L98-L100)).
In `redux-form`, it looks like `e.preventDefault` is called ([see relevant lines here](https://github.com/erikras/redux-form/blob/a8a8fd452127ac2acc10e99dd0ceb9234488778b/src/ConnectedField.js#L188)).

This is just a guess; I didn't dig too much into `react-final-form` or `redux-form`.

**Comment by kavink** [comment] 2018-02-17 03:58
@newyork-anthonyng Thanks a ton!!! I thought this will work : https://codesandbox.io/s/zlv7kmmyp 
But looks like it does not see to behave today ... still plowing through..

**Comment by newyork-anthonyng** [comment] 2018-02-17 04:52
@kavink I think this might have solved it?? (https://codesandbox.io/s/8x167ww6kj)

```diff
<Downshift
    {...input}
+    onInputValueChange={(inputValue) => {
+      input.onChange(inputValue);
+   }}
-    onStateChange={({ inputValue }) => {
-      return input.onChange(inputValue);
-    }}
>
```

**Comment by kavink** [comment] 2018-02-17 08:11
Thanks a lot!!! Yes that works.... Even I got to same solution, but then I hit another issue , changing ```<input``` to Material UI ```TextField``` with ```react-popper``` the ``` isOpen``` would never become ```true```...I then  just spend last hour or so just migrating to ```react-autosuggest``` Got that working like this with ```final-form``` so I'm good for now...   @kentcdodds  The sandbox from @newyork-anthonyng might be good to be posted to README. obviously instead of ```<input``` Material ui field is used, it would make a very good example for others.... Thanks a lot ! learnt a lot more than I started debugging this...

**Comment by kentcdodds** [comment] 2018-02-17 12:25
Thanks @newyork-anthonyng!

@kavink, I'm glad you got something that will work for your use cases.

If someone wants to add a react final form example to the README that would be great. The codesandbox currently has a lot of distraction around it so if we could simplify it that would be great. Also, it's probably not good to spread the `input` object across `<Downshift>` like that considering it will apply an `onChange` method and who knows what else to the downshift props....

**Comment by austintackaberry** [comment] 2018-02-18 04:03
@kentcdodds I would like to work with @newyork-anthonyng to clean up the react final form example and add it to the README

**Comment by kentcdodds** [comment] 2018-02-18 04:10
Super! Thanks @austintackaberry! I'll be happy to review it when you've got a PR ready :)

**Comment by kavink** [comment] 2018-02-21 19:32
@newyork-anthonyng @austintackaberry  @kentcdodds based on this: https://github.com/final-form/react-final-form/issues/162  Erik created a polished example and posted in README in react-final-form: https://codesandbox.io/s/qzm43nn2mj

**Comment by kentcdodds** [comment] 2018-02-21 22:46
Awesome! Who wants to open a pull request to add this to the README?

**Comment by austintackaberry** [comment] 2018-02-22 00:09
Done!

**Comment by omorhefere** [comment] 2018-07-01 18:01
@newyork-anthonyng What does {...input} do?

**Comment by newyork-anthonyng** [comment] 2018-07-01 21:31
Hi @omorhefere 

See below for an example of what the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) does in React.
```jsx
const myAttributes = {
  name: "Anthony",
  lastName: "Ng"
};
<MyComponent name={myAttributes.name} lastName={myAttributes.lastName} />

// is the same as...

<MyComponent {...myAttributes} />
```

**Comment by totymedli** [comment] 2019-05-01 01:33
Based on this thread, I will sum what worked for me.

Add these props to `<Downshift>`:
```
<Downshift
  onInputValueChange={(inputValue) => {
    this.props.input.onChange(inputValue);
  }}
  selectedItem={this.props.input.value}
>
```

Conditionally render the input based on the shown suggestion count:
```
<TextField
  InputProps={getInputProps(this.state.shownSuggestionsLength == 0 ? { value: inputValue, ...this.props.InputProps } : this.props.InputProps)}
/>
```

Of course I need to store the currently shown suggestion for this via `setState`.

**Comment by towry** [comment] 2019-06-29 14:57
My solution:

```ts
// Apply the onBlur on input element.
// selectedItem, selectItem is from downshift.

const { onFocus, onBlur, ...inputProps } = getInputProps({
  placeholder: 'Search ...',
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.value) {
      clearSelection();
    }
  },
  // allowing user input.
  onBlur: (e: React.ChangeEvent<HTMLInputElement>) => {
    let label = e.target.value;

    if (selectedItem) {
      if (selectedItem.label === label) {
        return;
      }
    }

    selectItem({
      label: e.target.value,
    })
  }
})
```

**Comment by mikejw** [comment] 2021-05-07 11:26
> My solution:
> 
> ```ts
> // Apply the onBlur on input element.
> // selectedItem, selectItem is from downshift.
> 
> const { onFocus, onBlur, ...inputProps } = getInputProps({
>   placeholder: 'Search ...',
>   onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
>     if (!e.target.value) {
>       clearSelection();
>     }
>   },
>   // allowing user input.
>   onBlur: (e: React.ChangeEvent<HTMLInputElement>) => {
>     let label = e.target.value;
> 
>     if (selectedItem) {
>       if (selectedItem.label === label) {
>         return;
>       }
>     }
> 
>     selectItem({
>       label: e.target.value,
>     })
>   }
> })
> ```

Where did you put this code?

**Comment by philmetzger** [comment] 2022-12-02 12:11
Hey, trying this out but the problem with using selectItem is then I get this:
`Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

I am using Formik to wrap this.

**Comment by silviuaavram** [comment] 2022-12-02 12:16
are you also controlling `selectedItem` via prop?

**Comment by philmetzger** [comment] 2022-12-02 12:21
i dont think so:

```
const AdvancedSelect = ({
  placeholder,
  onChange,
  onSelect,
  status,
  footer,
  value,
  onInputChange,
  options,
  renderOption,
  allowCustomValues,
}) => {
  const handleOnSelect = (selected, stateAndHelpers) => {
    onSelect && selected && onSelect(selected, stateAndHelpers);
    onChange && onChange(selected);
  };

  const handleInputChange = (event, clearSelection) => {
    if (!event.target.value) {
      clearSelection();
      return onChange && onChange(event.target.value);
    }

    if (!onInputChange) {
      return null;
    }

    return onInputChange(event.target.value);
  };

  return (
    <Downshift
      id="downshift"
      onChange={handleOnSelect}
      itemToString={(item) => (item ? item.name : '')}
      initialInputValue={value?.name}
    >
      {({
        selectItem,
        selectedItem,
        getInputProps,
        getItemProps,
        clearSelection,
        highlightedIndex,
        isOpen,
        openMenu,
        inputValue,
      }) => {
        return (
          <div className="relative">
            <Input
              size="s"
              status={status}
              {...getInputProps({
                placeholder,
                onChange: (e) => handleInputChange(e, clearSelection),
                onFocus: () => openMenu(),
                onBlur: (e) => {
                  e.preventDefault();
                  e.stopPropagation();

                  if (!allowCustomValues) {
                    return;
                  }

                  const label = e.target.value;

                  if (selectedItem) {
                    if (selectedItem.label === label) {
                      return;
                    }
                  }

                  onChange({ name: label, id: label, address: label });
                  selectItem(label); // THROWS WARNING: Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
                },
              })}
            />
            {isOpen ? (
              <div className="absolute z-50 mt-2 w-full rounded-lg border border-gray-200 bg-gray-100 shadow-xl shadow-gray-900/10 dark:shadow-black/50 dark:border-zinc-700 dark:bg-zinc-800">
                <div className="max-h-52 overflow-y-auto">
                  {options.map((option, index) => {
                    const isSelectedItem = selectedItem?.name === option?.name;
                    const isHighlighted = highlightedIndex === index;
                    const classes = classNames('cursor-pointer', {
                      'bg-gray-200 dark:bg-zinc-700': isHighlighted || isSelectedItem,
                    });

                    return (
                      <div {...getItemProps({ key: index, index, item: option })} className={classes}>
                        {renderOption(option)}
                      </div>
                    );
                  })}
                  {isOpen && options?.length === 0 && (
                    <div>
                      <NoResultsItem />
                    </div>
                  )}
                </div>
                {isOpen && footer && (
                  <div className="border-t border-gray-300 dark:border-zinc-700">
                    {cloneElement(footer, { inputValue })}
                  </div>
                )}
              </div>
            ) : null}
          </div>
        );
      }}
    </Downshift>
  );
};
```

**Comment by silviuaavram** [comment] 2022-12-02 12:29
What if you remove `initialInputValue={value?.name}` ?

**Comment by silviuaavram** [comment] 2022-12-02 12:30
Also, you are not using `getMenuProps` at all, please review the documentation on the recommendation to use the component.

**Comment by philmetzger** [comment] 2022-12-02 12:36
> What if you remove `initialInputValue={value?.name}` ?

Yeah made no difference.

Ok let me try refactor my component and see

**Comment by silviuaavram** [comment] 2022-12-02 12:37
The issue sounds to be coming from Formik's Input. You can grab the `value` returned by `getInputProps` and check if it switches from `undefined` to something defined or viceversa, and try to figure out why and fix it.

**Comment by philmetzger** [comment] 2022-12-02 12:41
BTW I also tried this example: https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/downshift/other-examples/prevent-reset-on-blur.js
And that also if i type something, and click outside (blur) the thing I typed disappears.

**Comment by philmetzger** [comment] 2022-12-02 12:54
Ah wait sorry, this is all my fault! Hard to explain, but basically its the way I set up by test case :) all good now

**Comment by silviuaavram** [comment] 2022-12-02 13:04
Good to know! Also consider using `useCombobox` instead of Downshift. Good luck!

**Comment by philmetzger** [comment] 2022-12-02 15:21
Just incase someone stumbles upon this and my "issue", i have solved it thanks to @silviuaavram suggestions. Converted to useCombobox and works much better.

This is how it looks now:
```
const AdvancedSelect = ({
  placeholder,
  onChange,
  onSelect,
  status,
  footer,
  value,
  onInputChange,
  options,
  renderOption,
  allowCustomValues,
}) => {
  const [selectedItem, setSelectedItem] = useState(value ? { name: value } : null);
  const { isOpen, getMenuProps, getInputProps, highlightedIndex, getItemProps, inputValue, selectItem, setInputValue } =
    useCombobox({
      items: options,
      itemToString(item) {
        return item ? item.name : '';
      },
      selectedItem,
      onSelectedItemChange: ({ selectedItem: newSelectedItem }) => {
        if (onSelect) {
          onSelect && onSelect(newSelectedItem);
        } else {
          setSelectedItem(newSelectedItem);
          onChange && onChange(newSelectedItem);
        }
      },
    });

  const handleInputChange = (event, clearSelection) => {
    if (!event.target.value) {
      clearSelection();
      return onChange && onChange(event.target.value);
    }

    if (!onInputChange) {
      return null;
    }

    return onInputChange(event.target.value);
  };

  return (
    <div>
      <div className="relative">
        <Input
          size="s"
          status={status}
          {...getInputProps({
            placeholder,
            onChange: (e) => handleInputChange(e, () => selectItem(null)),
            onBlur: (e) => {
              e.preventDefault();
              e.stopPropagation();

              if (!allowCustomValues) {
                setInputValue('');
                return;
              }

              const label = e.target.value;

              if (selectedItem) {
                if (selectedItem.name === label) {
                  return;
                }
              }

              onChange && onChange(label);
            },
          })}
        />
      </div>
      <ul {...getMenuProps()} className="relative" id="downshift" aria-labelledby="downshift">
        {isOpen ? (
          <div className="absolute z-50 mt-2 w-full rounded-lg border border-gray-200 bg-gray-100 shadow-xl shadow-gray-900/10 dark:shadow-black/50 dark:border-zinc-700 dark:bg-zinc-800">
            <div className="max-h-52 overflow-y-auto">
              {options.map((option, index) => {
                const isSelectedItem = selectedItem?.name === option?.name;
                const isHighlighted = highlightedIndex === index;
                const classes = classNames('cursor-pointer', {
                  'bg-gray-200 dark:bg-zinc-700': isHighlighted || isSelectedItem,
                });

                return (
                  <div {...getItemProps({ key: index, index, item: option })} className={classes}>
                    {renderOption(option)}
                  </div>
                );
              })}
              {options?.length === 0 && (
                <div>
                  <NoResultsItem />
                </div>
              )}
            </div>
            {footer && (
              <div className="border-t border-gray-300 dark:border-zinc-700">
                {cloneElement(footer, { inputValue })}
              </div>
            )}
          </div>
        ) : null}
      </ul>
    </div>
  );
};
```
