### ISSUE TITLE
Keep the menu open when scrolling the page on the mobile screen

### ISSUE THREAD

**Issue by lixualinta** [paypal/downshift#454] opened 2018-06-05 06:55 UTC
* `downshift` version: V1.31.15
* `node` version: V8.9.3
* `npm` (or `yarn`) version: 1.3.2

What you did:
On a mobile phone (or use the chrome developer tool), type something in the input field to open the menu open, then use the finger to scroll the screen

What happened:
If the area the finger press when started scrolling is in the input field or on the menu, the menu stays open;
If the area the finger press while started scrolling is outside of the input/menu area, the menu is closed

Reproduction repository:
https://github.com/mui-org/material-ui/blob/master/docs/src/pages/demos/autocomplete/IntegrationDownshift.js
https://material-ui.com/demos/autocomplete/#downshift

Problem description:
The menu is closed when scrolling the screen 

Suggested solution:
Keep the menu open when scrolling the screen no matter where the finger is when scrolling

**Comment by kentcdodds** [comment] 2018-06-12 23:08
This is definitely possible with the built-in capabilities. I think you might need to use a `stateReducer` (see the docs). You may alternatively consider using control props and controlling the `isOpen` state (see the docs).

As this is a question and not a bug or feature that we'll be making changes to the library for, I'll go ahead and close this. If you need further help, please join our community on spectrum and post to the help channel there: https://spectrum.chat/downshift

**Closed by kentcdodds** 2018-06-12 23:08 UTC
Labels: question
