### ISSUE TITLE
Keyboard selection is rudely interrupted and overridden by auto-complete mouse-enter actions.

### ISSUE THREAD

**Issue by tannerlinsley** [paypal/downshift#240] opened 2017-10-23 20:19 UTC
- `downshift` version: 1.16.0
- `node` version: 8.5.0
- `npm` (or `yarn`) version: yarn 1.0.2

### Description
In any downshift configuration (at least thus far in my experience), the mouse position will fire (and select whatever is underneath it) immediately after an arrow-selecting and shift-arrow-paging event.

### Replication
1. Navigate to any example: http://downshift.netlify.com/?selectedKind=Examples&selectedStory=basic&full=0&down=1&left=1&panelRight=0
2. Open the menu by changing the input
3. Make sure there are multiple "pages" of options.
4. Place your cursor over the first option in the list
5. Using the down-arrow on your keyboard, navigate down the list
6. As soon as your arrow-down action selects an option beyond the visible set (either by arrowing-down on the last option, or shift-arrowing-down to change the whole page) the option underneath the cursor position will subsequently be selected.

### Expected
I would expect the cursor to not activate an option while using arrow navigation, unless of course, the cursor is moved.

**Comment by tannerlinsley** [comment] 2017-10-23 20:24
Code origin is easy to locate: https://github.com/paypal/downshift/blob/master/src/downshift.js#L637, but the solution to this problem could be more difficult than I thought.

**Comment by kentcdodds** [comment] 2017-10-23 20:25
Yep, I've seen and experienced this before. Interestingly, Google avoids this problem and hides the cursor:

![google-example](https://user-images.githubusercontent.com/1500684/31911453-ef2be9de-b7fd-11e7-98b0-d27065deb17d.gif)

I think we could do something similar. I definitely welcome a pull request to improve this experience. I think that most folks would prefer this and others wouldn't notice if we changed this.

**Comment by kentcdodds** [comment] 2017-10-23 20:26
As for a solution, I'm not 100% certain the best way to do it. Definitely open to ideas.

**Comment by tannerlinsley** [comment] 2017-10-23 20:26
I'm curious if a mouse move event would fire in the same situation.

**Comment by tannerlinsley** [comment] 2017-10-23 20:27
That would probably bring some debouncing or cancelling issues to mind, but theoretically would work.  I feel there is a simpler solution though...

**Comment by philipyoungg** [comment] 2017-10-24 05:39
@kentcdodds @tannerlinsley I'll look at this tonight! I'm also developing similar component for client work so let's see what I can do.

**Comment by philipyoungg** [comment] 2017-10-25 07:24
After thinking for a while, I think this could work (theoretically). Here's how:

1. we need to add a new state. Let's call it `isArrowButtonClicked` for now.
2. on `componentWillMount`, add event listener that binds to `onkeyup`. If `this.state.isOpen` and key UP/DOWN is pressed, change `this.state.isArrowButtonClicked` to true.
3. Similarly, on `componentWillMount`, add event listener that binds to `onmousemove`. If `this.state.isOpen` and `this.state.isArrowButtonClicked` is true, then change it to false
3. Lastly, we only run the `onMouseEnter` event listener on item props if `this.state.isArrowButtonClicked` is true. https://github.com/paypal/downshift/blob/master/src/downshift.js#L637

Love to hear any improvement!

cc: @kentcdodds @tannerlinsley

**Comment by kentcdodds** [comment] 2017-10-25 13:07
Thanks for the idea @philipyoungg,

I'm not sure I understand the purpose of the `isArrowButtonClicked`... Honestly this doesn't appear to have anything to do with whether you click the toggle button or if there's even a toggle button at all...

I think that it would be easier to see solutions to this than hear it explained. Anyone can feel free to open a PR. It may not get merged right away or at all depending on how complicated it is, but that will be much more likely to get merged if it's shown in a PR rather than explained in text :)

**Comment by philipyoungg** [comment] 2017-10-25 15:19
@kentcdodds IsArrowButtonClicked is a state that monitors whether user pressed key up / key down *while* the dropdown is open. 

The problem is mouse event fired when user choosing the dropdown item on arrow up / arrow down right? 

The only responsibility of the state is to disable the Mouse event when the state is true. 

The state will return to false as soon as user moves the Mouse.

**Comment by kentcdodds** [comment] 2017-10-25 15:21
Hmmm... the `isArrowButtonClicked` name just isn't working for me.... But feel free to open a PR and we can talk about it there.

Also, I wonder whether [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) could help us here.

**Comment by cmmartin** [comment] 2017-11-29 23:42
`/s/isArrowButtonClicked/isArrowButtonPressed`

Fingers don't click :)

**Comment by ibrahima** [comment] 2017-12-12 05:29
My 2c, I think part of the naming confusion is because it's not an arrow button, but an arrow key. Button makes web developers think of `<button>` I think 😛.

`isArrowKeyPressed`?

**Comment by kentcdodds** [comment] 2017-12-12 05:33
Thanks @ibrahima. Yes, I do like `isArrowKeyPressed` better :+1:

Still not sure I follow the suggested solution well, but a PR would help me understand I think.

**Comment by kentcdodds** [comment] 2018-01-04 20:15
This was mistakenly closed.

**Comment by kentcdodds** [comment] 2018-03-20 20:13
This was solved a while back. Forgot to close the issue.

**Closed by kentcdodds** 2018-03-20 20:13 UTC
Labels: enhancement, help wanted
