### ISSUE TITLE
Down arrow key selection gets confused with the mouse selection when options scroll

### ISSUE THREAD

**Issue by MarkFalconbridge** [paypal/downshift#296] opened 2018-01-04 15:03 UTC
* `downshift` version: 1.22.5
* `node` version:9.2.1

What you did:

Using the example at https://codesandbox.io/s/zx1kj58npl, open the drop down and move the mouse over one of the options. That highlights the option. Then use the down arrow on the keyboard to go through the options ensuring to try to get to the items currently scrolled out of view. 

What happened:

The highlighted item follows the user keyboard input until the next item results in the browser scrolling the list. At this point the highlighted item is set to the item under the cursor rather than the next one in the list.

Reproduction repository:

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment] 2018-01-04 20:16
I think this is a duplicate of https://github.com/paypal/downshift/issues/240

I'll close this to consolidate the issues.

**Comment by kentcdodds** [comment] 2018-01-04 20:16
Thanks!

**Closed by kentcdodds** 2018-01-04 20:16 UTC
