### ISSUE TITLE
onStateChange function called when selecting an item (it's supposed to call just onChange)

### ISSUE THREAD

**Issue by titanve** [paypal/downshift#237] opened 2017-10-21 17:34 UTC
- `downshift` version: 1.14.0
- `node` version: 6.9.4
- `npm` (or `yarn`) version: 1.2.1

Relevant code or config

```javascript
<ClienteAutocomplete
  items={this.state.liveresult}
  onChange={selectedItem => {
  selectedItem != null &&
    this.handleOnChange(selectedItem.cliid);
  }}
  // console.log(`onChange: ${selectedItem.cliid}`)}
  itemToString={this.itemToString}
  onStateChange={changes => {
    changes.hasOwnProperty("inputValue") &&
      this.getClienteLive(changes.inputValue);
  }}
/>

// ClienteAutocomplete component
import React, { Component } from "react";
// import PropTypes from "prop-types";
import Downshift from "downshift";

let ClienteAutocomplete = ({
  items,
  onChange,
  itemToString,
  onStateChange
}) => {
  return (
    <Downshift
      onChange={onChange}
      itemToString={itemToString}
      onStateChange={onStateChange}
    >
      {({
        getInputProps,
        getButtonProps,
        getItemProps,
        isOpen,
        clearSelection,
        inputValue,
        selectedItem,
        highlightedIndex
      }) => (
        <div>
          <input
            {...getInputProps({
              placeholder: "Buscar cliente..."
            })}
          />
          {selectedItem ? (
            <button {...getButtonProps()} onClick={clearSelection}>
              Limpiar
            </button>
          ) : null}
          {isOpen ? (
            <div style={{ border: "1px solid #ccc" }}>
              {items.map((item, index) => (
                <div
                  {...getItemProps({ item })}
                  key={item.cliid}
                  style={{
                    backgroundColor:
                      highlightedIndex === index ? "gray" : "white",
                    fontWeight: selectedItem === item ? "bold" : "normal"
                  }}
                >
                  {itemToString(item)}
                </div>
                // ))
              ))}
            </div>
          ) : null}
        </div>
      )}
    </Downshift>
  );
};

export default ClienteAutocomplete;


```

What you did:

What happened: When I select an item downshift component is calling `onStateChange` function when it's supposed to call just `onChange`

Reproduction repository:

Problem description:

Suggested solution:

**Comment by tansongyang** [comment] 2017-10-21 21:53
Hi there. This is expected behavior (unless I'm misunderstanding something). See the docs about [`onStateChange`](https://github.com/paypal/downshift#onstatechange) (emphasis mine):

> This function is called **anytime the internal state changes**. This can be useful if you're using downshift as a "controlled" component, where you manage some or all of the state (e.g. isOpen, selectedItem, highlightedIndex, etc) and then pass it as props, rather than letting downshift control all its state itself. The parameters both take the shape of internal state ({highlightedIndex: number, inputValue: string, isOpen: boolean, selectedItem: any}) but differ slightly.

It has to be called any time internal state changes, which includes when an item is selected.

In your case, you could probably keep track of the currently selected item. Then, in `onStateChange`, you can check if `changes.selectedItem` has changed or not.

Because this is expected behavior, I'm closing this issue.

**Closed by tansongyang** 2017-10-21 21:53 UTC
