### ISSUE TITLE
Dropdown select does not work on iOS (safari)

### ISSUE THREAD

**Issue by vonwao** [paypal/downshift#443] opened 2018-05-03 23:02 UTC
* `downshift` version: http://downshift.netlify.com/
* `node` version:
* `npm` (or `yarn`) version:

What you did:
Tried dropdown example

What happened:
I can open dropdown by clicking button, but I can't select any other item

**Comment by Joroze** [comment] 2018-05-05 15:25
Hi, I believe this also occurs on FireFox/IE11 if you have a Semantic UI Dropdown HTML structure like the following:

Basically, having your item elements within the menu div element, all under the root button dropdown element.

`
<button class="ui dropdown button">
  <i class="filter icon"></i>
  <span class="text">Filter Posts</span>
  <div class="menu">
    <div class="ui icon search input">
      <i class="search icon"></i>
      <input type="text" placeholder="Search tags...">
    </div>
    <div class="divider"></div>
    <div class="header">
      <i class="tags icon"></i>
      Tag Label
    </div>
    <div class="scrolling menu">
      <div class="item">
        <div class="ui red empty circular label"></div>
        Important
      </div>
      <div class="item">
        <div class="ui blue empty circular label"></div>
        Announcement
      </div>
      <div class="item">
        <div class="ui black empty circular label"></div>
        Cannot Fix
      </div>
      <div class="item">
        <div class="ui purple empty circular label"></div>
        News
      </div>
      <div class="item">
        <div class="ui orange empty circular label"></div>
        Enhancement
      </div>
      <div class="item">
        <div class="ui empty circular label"></div>
        Change Declined
      </div>
      <div class="item">
        <div class="ui yellow empty circular label"></div>
        Off Topic
      </div>
      <div class="item">
        <div class="ui pink empty circular label"></div>
        Interesting
      </div>
      <div class="item">
        <div class="ui green empty circular label"></div>
        Discussion
      </div>
    </div>
  </div>
</button>
`

**Comment by Joroze** [comment] 2018-05-05 15:47
This seems to also occur on Firefox/IE11 in cases where you have a root button element, and a div child element (dropdown menu), with div child (dropdown items) in the menu.

For example, an HTML structure like this Semantic UI React component
https://react.semantic-ui.com/modules/dropdown#dropdown-example-input

**Comment by kentcdodds** [comment] 2018-05-29 20:37
I'm sorry, I don't have time to look into this myself. But I'd love for this to be fixed once and for all. iOS Safari has been a bit of a pain.

**Comment by aMollusk** [comment] 2018-05-29 23:40
I'm more than happy to help, but I can't reproduce this on a real iOS device. 

Which emulator are you using @alfredringstad - I'll take a look if I can get one running.

As a side note: I've noticed that storybook behaves kind of strangely on iOS because of the iFrame (the white container). Ensuring that the grey menus are out of the way seems to resolve some unexpected behaviour.

**Comment by vonwao** [comment] 2018-05-31 23:43
@aMollusk it seems to be working now for me, although there is a noticeable lag, between the time you touch an item and when it highlights and selects.

**Comment by alfredringstad** [comment] 2018-06-06 22:00
So I finally had some time to look into this. While I thought this was related to the original issue, I now realised that my problem might not be what @vonwao intended. If that is the case, I'm sorry for stealing this issue.

My problem exists when the toggle button is a `<button>` element. When I press the toggle button the first time, it opens the menu as it should. I can select other items in the list, or press anywhere else on the page to trigger the blur event and close the menu. However, if I instead press the toggle button again (so first toggle button to open, then toggle button to close), the menu stays open. This happens in Safari on iOS. I tried it out using the Xcode simulator on an iPhone 6 running iOS 9.

The problem seems to be that Safari on iOS triggers a blur event before the onClick event, if the button was manually focused. This causes, as I posted in a comment above, that the menu is first reset (isOpen = false) and then toggled (isOpen = true). I think the desired behaviour is that the menu should only be toggled (isOpen = false).

To fix this, I found a solution where we can store the blur event target and compare it to the active selection and see if it's the same element that is focused again. In that case we shouldn't trigger the blur action.

This code example would solve this problem:
```js
  button_handleBlur = event => {
    const target = event.target; // Need to save this reference since it's not available on event when we're inside the setTimeout function
    // Need setTimeout, so that when the user presses Tab, the activeElement is the next focused element, not body element
    setTimeout(() => {
      if (
        !this.isMouseDown &&
        (this.props.environment.document.activeElement == null ||
          this.props.environment.document.activeElement.id !== this.inputId) &&
        this.props.environment.document.activeElement !== target // Make sure same element is not re-focused
      ) {
        this.reset({type: Downshift.stateChangeTypes.blurButton})
      }
    })
  }
```

Note that this is only a problem when the toggle button is a `<button>` element.

Another possible workaround (that could have some more side effects) is to use `preventDownshiftDefault` on the onBlur method:

```js
<button
  {...getToggleButtonProps({
    onBlur: e => (e.preventDownshiftDefault = true) // Workaround for a Downshift bug in Safari on iOS where onBlur is wrongfully triggered before onClick
  })}
>
  Toggle button
</button>;
```

I'd happily create a pull request if you think my code example is a good solution for this.

**Comment by kentcdodds** [comment] 2018-06-07 04:32
Let's see a pull request with your suggested solution. Thank you!

**Comment by kentcdodds** [comment] 2018-08-06 13:43
Ah, now that's no good! Could you investigate what changed and caused the bug?

**Comment by Drapegnik** [comment] 2018-08-11 16:30
Sorry, it was my issue: I did not use `getMenuProps` and `targetWithinDownshift(event.target, false)` return `false`, so it was interpreted as outside click.

**Comment by kitfit-dave** [comment] 2018-10-02 09:58
Quick update: I was using (much like the material ui example) Paper as the menu container, spreading getMenuProps() - if I wrap this in a div it works as expected.

I have not had time to look at why using the Paper as the menu does not work... though I'd guess that it's due to missing refKey - they seem to have removed most of the ref stuff from material ui yes? (see https://github.com/mui-org/material-ui/issues/5532) - I'm not entirely sure how to use findDOMNode to workaround this though.

I'd say that I might have to give up trying to use material ui composite components directly and always wrap them in divs... Sorry to ramble.

**Comment by kentcdodds** [comment] 2018-10-05 18:05
So this appears to be more with how downshift is (mis)used than downshift itself.

If someone would like to contribute some documentation to help people avoid using it incorrectly in this way that'd be great! But I'm going to go ahead and close this as I'm trying to clean house a bit :)

**Closed by kentcdodds** 2018-10-05 18:05 UTC
Labels: help wanted, needs investigation
