### ISSUE TITLE
prop getters should return all current prop values

### ISSUE THREAD

**Issue by ellismarkf** [paypal/downshift#225] opened 2017-10-14 00:32 UTC
- `downshift` version: 1.11.1
- `node` version: 6.9.1
- `npm` (or `yarn`) version: 0.27.5

*Relevant code or config*

```javascript

import React from 'react';
import Downshift from 'downshift';

function AutocompleteWindowItem(props) {
  const {
    getItemProps,
    highlightedIndex,
    selectedItem,
  } = props.downshiftProps;
  return (
    <div
      className="JPMC__Autocomplete__item"
      {...getItemProps({ item: props.item })}
      style={{
        backgroundColor: highlightedIndex === props.index ? 'gray' : 'white',
        fontWeight: selectedItem === props.item ? 'bold' : 'normal',
      }}
    >
      {props.item}
    </div>
  );
}

function AutocompleteWindow(props) {
  const Item = props.renderItem;
  return (
    <div className="JPMC__Autocomplete__window">
      {props.items
        .map((item, index) => (
            <Item
              key={item}
              item={item}
              index={index}
              downshiftProps={props.downshiftProps}
            />
          )
        )}
    </div>
  )
}

function Nullable(props) {
  return props.isNull ? null : props.children;
}

function AutocompleteDOM(items, inputProps) {
  return downshift => (
    <div className="JPMC__Autocomplete__container">
      <input {...downshift.getInputProps(inputProps) } />
      <Nullable isNull={!downshift.isOpen}>
        <AutocompleteWindow
          items={items}
          renderItem={AutocompleteWindowItem}
          downshiftProps={downshift}
        />
      </Nullable>
    </div>
  );
}

function Autocomplete(props) {
  return (
    <Downshift {...props.downshiftProps}>
      {AutocompleteDOM(props.items, props.inputProps)}
    </Downshift>
  );
}

function TypeAhead(props) {
  return forwarded => (
    <Autocomplete
      inputProps={{name: forwarded.name, ...props.inputProps}}
      items={props.items}
      downshiftProps={props.downshiftProps}
    />
  );
}

function LabeledFormPart({ label, name, width, children, extraClasses, ...props }) {
  const formattedWidth = width
  ? `${width.value}${width.unit}`
  : null;
const style = width ? {width: formattedWidth} : null;
const baseClass = 'LabeledFormPart';
const classes = extraClasses ? `${baseClass} ${extraClasses}` : baseClass; 
  return (
    <div className={classes} style={style}>
      <label htmlFor={name}>{label}</label>
      {children({ name, ...props })}
    </div>
  );
}

class Form extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      form: {
        city: '',
      }
    }
    this.handleInputChange = this.handleInputChange.bind(this);
    this.handleTypeAheadChange = this.handleTypeAheadChange.bind(this);
  }

  handleInputChange(event) {
    this.setState({
      form: {
        ...this.state.form,
        [event.target.name]: event.target.value
      }
    })
  }

  handleTypeAheadChange(value, downshift) {
    const { name } = downshift.getInputProps();
    this.setState({
      form: {
        ...this.state.form,
        [name]: value,
      }
    });
  }

  render() {
    return (
      <LabeledFormPart
        label="Client's Legal name"
        name="legalName"
      >
        {TypeAhead({
          items: ['apps', 'widgest', 'derricks'],
          downshiftProps: {
            onChange: this.handleTypeAheadChange
          },
          inputProps: {
            placeholder: 'Enter a name',
            name: 'legalName',
            value: this.state.form.legalName,
            onChange: this.handleInputChange
          }
        })}
      </LabeledFormPart>     
    );
  }
}

```

*What you did:*
I expect calling `downshift.getInputProps();` in `Form.handleTypeAheadChange` to return the _current and complete_ set of props on the `input` element, so that I can dynamically set a piece of state in a parent component with the `name` property set on the `Downshift` input element.

*What happened:*
Calling `downshift.getInputProps()` returns just the _default_ set of props on the input object as defined [in the source](https://github.com/paypal/downshift/blob/master/src/downshift.js#L536), without the `name` or the `placeholder` props that were passed to the input element when it was created.  

*Problem description:*
I'm not sure if it's a naming issue, a usage issue (user error), or if it's really a problem at all.  It seems like `getInputProps` should be able to get all props currently set on the rendered input element, including those passed to the element in the child callback function, so that developers could do something like:

```javascript
ReactComponent.handleDownshiftChange(value, downshiftState) {
  const { name, placeholder, ...etc } = downshiftState.getInputProps();
  this.setState({
    [name]: value
  });
```
Similar to the way you'd typically handle events when building controlled input/select elements in React. But maybe I'm misunderstanding what `getInputProps()` actually does?

*Suggested solution:*
Since I'm not sure it's actually a _problem_, I'm not exactly sure how to suggest a solution.  If I'm simply using the method incorrectly, I guess the solution could be just letting me know :wink:.  If what I'm proposing is a valid use case, then I see (at least) two possible solutions, which aren't mutually exclusive:

1. Update the `getInputProps` method to return the default props, along with any additional props (ie, `...rest`, and `...eventHandlers`) that have been set on the input element.
2. Change the name of `getInputProps` to `setInputProps`.  The current implementation seems like it's actually setting, rather than getting, props on the input element (unless, again, I'm misunderstanding). Changing the name to `setInputProps`, in my opinion, would make the intent of the method clearer, and would also open the `getInputProps` method name for another implementation that returned _all_ the props set on an input element.

If option 2 is a viable solution, the code could look something like this:

```javascript
<Downshift>
  {({ setInputProps }) => (
    <input {...setInputProps({ name: 'name', placeholder: 'Enter name', ...etc })} />
    ...
  )}
</Downshift>

SomeOtherComponent.handleDownshiftChange(value, downshiftState) {
  const { name } = downshiftState.getInputProps();
  SomeOtherComponent.setState({
    [name]: value
  });
}
```
Hopefully I've explained the issue well enough, but please feel free to let me know if you need more info!  I'm happy to try submitting a PR, but I wanted to ask about the usage and vision before doing that, because I'm not sure I'm correctly using the method, or that my suggested changes align with the library.

Thanks for all your hard work.  This is a great library!

Cheers!

**Comment by kentcdodds** [comment] 2017-10-14 00:40
Thanks for the thorough issue! Sorry, I'm on my phone right now, but if I understand correctly, I believe we do what you are suggesting already...

https://github.com/paypal/downshift/blob/master/src/downshift.js#L547

Am I missing something?

**Comment by ellismarkf** [comment] 2017-10-14 01:00
Thanks a bunch for the quick response!

I had a feeling I wasn't explaining myself very well :laughing:.  

I'll give it another go:

Calling `getInputProps` works as expected when calling it from the child callback function (or some child component of that function), and passing it parameters, ie:

```javascript
<Downshift>
  {({ getInputProps }) => (
    <input {...getInputProps({ name: 'name', placeholder: 'Enter name', ...etc })} />
    ...
  )}
</Downshift>
```

The above code works as expected.  Inspecting the markup in Developer Tools shows that the passed `name` and `placeholder` properties do indeed exist on the `input` element.

What doesn't work (at least for me) is when you try to call `getInputProps()` with no parameters, outside of a render function, ie in an event handler component method, especially when a parent component doesn't render a `<Downshift />` component directly, like so:

```javascript
class Form extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      form: {
        city: '',
      }
    }
    this.handleTypeAheadChange = this.handleTypeAheadChange.bind(this);
  }

  handleTypeAheadChange(value, downshift) {
    /**
      * this doesn't work.  `name` is undefined, as are any other props that aren't explicitly passed here.
      * all that gets returned from this call are the default props, which makes sense, since I'm not passing
      * any additional parameters here.  but since I know that my input element has a `name` property,
      * which I passed in the child callback function, it seems like `getInputProps` ought to return that.  
      */
    const { name } = downshift.getInputProps();
    this.setState({
      form: {
        ...this.state.form,
        [name]: value,
      }
    });
  }

  render() {
    return (
      // this component passes the `name` property to its chlid, `TypeAhead`
      <LabeledFormPart
        label="Client's Legal name"
        name="legalName"
      >
        // TypeAhead is a wrapper around `<Downshift />` that passes props down as necessary
        {TypeAhead({
          items: ['apps', 'widgest', 'derricks'],
          downshiftProps: {
            onChange: this.handleTypeAheadChange
          },
          inputProps: {
            placeholder: 'Enter a name',
            name: 'legalName',
            value: this.state.form.legalName,
            onChange: this.handleInputChange
          }
        })}
      </LabeledFormPart>     
    );
  }
}
```

Thanks again for the fast response!  :smile:

**Comment by Dajust** [comment] 2017-10-14 03:31
I was just about to file this issue before I saw this, thank you @ellismarkf for saving me the time :smile: 

Hey @kentcdodds :wave: I finally tried downshift and it's been awesom :smile: Thanks you so much for this :pray: 

So the thing here is, we want more *unique* information about each `<Autocomplete />` instance we build with downshift. I belief @ellismarkf has done a good job explaining this but just as an addition, consider this:

When an event is fired on any native element like `<select />` for example, the handler of that event is passed the event object as a gateway to knowing all about the event. 
```
onChangehandler(event) {// do stuff with event}
```
Then, we usually do `event.target` to get all unique information about the dom element the event is fired on, like getting the element name for example.

This is the same expectation we have for each instance of the `<Autocomplete />` we make using downshift.

So if we have 2 Autocomplete instances, one for a country and the other for a state, for example.

```
<Autocomplete name="countryAutocomplete" placeholder="select a country" />
<Autocomplete name="stateAutocomplete" placeholder="select a state" />
```
We want the onChange handler of these elements to be passed not just `selectedItem`, but something that provides some unique properties for each element, like their names, so we can set our Parent Component State Accordingly.
What we have now:
```
onChange(selectedItem, stateAndHelpers) {
        // stateAndHelpers.getInputProps() is what we expected to have done this job
	// but unfortunately, the method is only for setting some default and custom props on the underlying
	// input element, but not to return the custom props 
       // So doing something like this won't work:
 
    const { name } = stateAndHelpers.getInputProps();
    this.setState({
      form: {
        ...this.state.form,
        [name]: value,
      }
    });
}
```
What we're actually asking:

```
onChange(selectedItem, stateAndHelpers) {
    const { name } = stateAndHelpers.getProps(); // somthing like this

    this.setState({
      form: {
        ...this.state.form,
        [name]: value,
      }
    });
}
```
Currently, my workaround this is having an intermediary inline function on each element, which receives the selectedItem from downshift, then calls  the Parent Component updater function with the props and some element unique values. Something like this

```
<Autocomplete 
  onChange={
    (selectedItem) => onAutocompleteChange("stateAutocomplete", selectedItem)
  } 
  placeholder="select a state" />

// \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

onAutocompleteChange(elementName, selectedItem) {
    this.setState({
      form: {
        ...this.state.form,
        [elementName]: selectedItem,
      }
    });
}
```
This works but it's not so cool, if downshift could give us a way to set/get unique properties on the elements, we shouldn't be passing these extra inline functions in all Autocomplete instances.

Note: The unique properties don't necessarily need to be bound to the underlying input element. We just need to set it on the `<Autocomplete />` element, then get it from the onChange method. Such way, nobody cares about the underlying input element and or any implementation details.

Thank you agian @kentcdodds for donwshit :pray:

**Comment by kentcdodds** [comment] 2017-10-14 05:15
Hey Justice :wave:

Thanks for helping to clarify! That was really helpful!

Honestly, I think that having the inline arrow function is a great solution to this problem. It's more explicit. However, we do have a mechanism to uniquely identify a downshift component instance using the [id](https://github.com/paypal/downshift#id) prop which you can set, but not get from the instance (easily). I think that I wouldn't be opposed to spreading `this.props` across the `getStateAndHelpers` function (which is where `stateAndHelpers` comes from in that callback.

https://github.com/paypal/downshift/blob/c2c45aae6b964a9948f49ddba5e50c11d9e6e9f3/src/downshift.js#L333-L380

We already provide `itemToString` as a convenience, so I don't see any reason why we wouldn't be able to just spread all the props across.

To do this, we'd add `...this.props` above [this line](https://github.com/paypal/downshift/blob/c2c45aae6b964a9948f49ddba5e50c11d9e6e9f3/src/downshift.js#L354) then remove [this line](https://github.com/paypal/downshift/blob/c2c45aae6b964a9948f49ddba5e50c11d9e6e9f3/src/downshift.js#L335) and [this line](https://github.com/paypal/downshift/blob/c2c45aae6b964a9948f49ddba5e50c11d9e6e9f3/src/downshift.js#L372).

I don't think we'd need to update any tests (I'm pretty sure we already have a test that `itemToString` is available).

Then we'd want to update docs. Now things will be in 4 categories (not [three](https://github.com/paypal/downshift#child-callback-function)). We'd remove `itemToString` from [this table](https://github.com/paypal/downshift#actions). Then add a section below [`state` here](https://github.com/paypal/downshift#state) called `props` which wont need a table but simply a brief explanation that as a convenience, all props you pass to `<Downshift />` are forwarded along to you.

This should be a pretty simple change. I don't mind who implements it, but please follow [the contributing guidelines](https://github.com/paypal/downshift/blob/master/CONTRIBUTING.md) and add @ellismarkf and @Dajust as contributors with the `ideas` contribution type (and yourself as a `doc` and `code` contributor).

Thanks!

**Comment by Dajust** [comment] 2017-10-14 07:54
Let me do this one Kent :smile:

**Comment by Dajust** [comment] 2017-10-14 12:11
Hey @kentcdodds, the build keeps failing when I `npm run validate`.  I'm not sure how to proceed.
 
It seems linting the example projects is the cause of this, as they're importing files not in this project. I'm not exactly sure. Here's the log:
```
justice@:~/OpenSource/downshift$ npm run validate 

> downshift@0.0.0-semantically-released validate /home/justice/OpenSource/downshift
> kcd-scripts validate lint,build-and-test,test:cover,test:ts,test:ssr

[test:ts] npm run test:ts --silent exited with code 0
[build-and-test] [preact.cjs] 
[build-and-test] [preact.cjs] src/index.js → preact/dist/downshift.cjs.js...
[build-and-test] [react.umd] 
[build-and-test] [react.umd] src/index.js → dist/downshift.umd.js...
[build-and-test] [react.esm] 
[build-and-test] [react.esm] src/index.js → dist/downshift.esm.js...
[build-and-test] [react.umd.min] 
[build-and-test] [react.umd.min] src/index.js → dist/downshift.umd.min.js...
[build-and-test] [preact.esm] 
[build-and-test] [preact.esm] src/index.js → preact/dist/downshift.esm.js...
[build-and-test] [preact.umd] 
[build-and-test] [preact.umd] src/index.js → preact/dist/downshift.umd.js...
[build-and-test] [react.cjs] 
[build-and-test] [react.cjs] src/index.js → dist/downshift.cjs.js...
[build-and-test] [preact.umd.min] 
[build-and-test] [preact.umd.min] src/index.js → preact/dist/downshift.umd.min.js...
[test:ssr]  PASS  other/ssr/__tests__/index.js (31.606s)
[test:ssr]   ✓ does not throw an error when server rendering (33ms)
[test:ssr] 
[test:ssr] Test Suites: 1 passed, 1 total
[test:ssr] Tests:       1 passed, 1 total
[test:ssr] Snapshots:   0 total
[test:ssr] Time:        33.781s
[test:ssr] Ran all test suites.
[test:ssr] npm run test:ssr --silent exited with code 0
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/apollo.js
[lint]   8:8  error  Unable to resolve path to module 'react-apollo'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/axios.js
[lint]   2:19  error  Unable to resolve path to module 'axios'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/basic.js
[lint]   3:25  error  Unable to resolve path to module 'match-sorter'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/controlled.js
[lint]   3:25  error  Unable to resolve path to module 'match-sorter'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/multiple.js
[lint]   3:25  error  Unable to resolve path to module 'match-sorter'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/react-autosuggest.js
[lint]   2:25  error  Unable to resolve path to module 'match-sorter'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/react-instantsearch.js
[lint]   2:40  error  Unable to resolve path to module 'react-instantsearch/dom'         import/no-unresolved
[lint]   3:35  error  Unable to resolve path to module 'react-instantsearch/connectors'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/react-popper.js
[lint]   2:39  error  Unable to resolve path to module 'react-popper'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/semantic-ui.js
[lint]   2:25  error  Unable to resolve path to module 'match-sorter'  import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/windowing-with-react-tiny-virtual-list.js
[lint]   2:25  error  Unable to resolve path to module 'react-tiny-virtual-list'  import/no-unresolved
[lint]   3:25  error  Unable to resolve path to module 'match-sorter'             import/no-unresolved
[lint] 
[lint] /home/justice/OpenSource/downshift/stories/examples/windowing-with-react-virtualized.js
[lint]   2:20  error  Unable to resolve path to module 'react-virtualized'  import/no-unresolved
[lint]   3:25  error  Unable to resolve path to module 'match-sorter'       import/no-unresolved
[lint] 
[lint] ✖ 14 problems (14 errors, 0 warnings)
[lint] 
[lint] npm run lint --silent exited with code 1
--> Sending SIGTERM to other processes..
[test:cover] npm run test:cover --silent exited with code null
[build-and-test] [preact.esm] cross-env BUILD_ROLLUP=true BUILD_FORMAT=esm BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js exited with code null
[build-and-test] --> Sending SIGTERM to other processes..
[build-and-test] [react.umd] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=false NODE_ENV=development  rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js --sourcemap exited with code null
[build-and-test] [preact.umd.min] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=true NODE_ENV=production BUILD_PREACT=true rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js --sourcemap exited with code null
[build-and-test] [preact.cjs] cross-env BUILD_ROLLUP=true BUILD_FORMAT=cjs BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js exited with code null
[build-and-test] [react.cjs] cross-env BUILD_ROLLUP=true BUILD_FORMAT=cjs BUILD_MINIFY=false NODE_ENV=development  rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js exited with code null
[build-and-test] [react.esm] cross-env BUILD_ROLLUP=true BUILD_FORMAT=esm BUILD_MINIFY=false NODE_ENV=development  rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js exited with code null
[build-and-test] [preact.umd] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=false NODE_ENV=development BUILD_PREACT=true rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js --sourcemap exited with code null
[build-and-test] [react.umd.min] cross-env BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=true NODE_ENV=production  rollup --config ./node_modules/kcd-scripts/dist/config/rollup.config.js --sourcemap exited with code null
[build-and-test] npm run build-and-test --silent exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! downshift@0.0.0-semantically-released validate: `kcd-scripts validate lint,build-and-test,test:cover,test:ts,test:ssr`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the downshift@0.0.0-semantically-released validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justice/.npm/_logs/2017-10-14T10_59_58_221Z-debug.log
justice@:~/OpenSource/downshift$ 

```

**Comment by kentcdodds** [comment] 2017-10-14 13:09
Sorry about that @Dajust! Could you update your branch? I just pushed a small change. Instead of `npm install` and `npm run validate`, now you can simply run `npm run setup` and it'll get everything set up and validated for you.

The problem is that we have a `stories` directory with a `package.json` so those dependencies also need to be installed. I simplified things by just having a `setup` script that does all this stuff for you. Let me know if that doesn't work :)

**Closed** 2017-10-16 15:53 UTC
Labels: enhancement, good first issue, help wanted
